apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Irshad-infracloud4/PostgressIrshad.git
    targetRevision: HEAD
    path: monitor/templates/kube-prometheus-stack/
    helm:
      valueFiles:
        - test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
      - CreateNamespace=true               
      - ServerSideApply=true