apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.0
    helm:
      values: |
        auth:
          username: myuser
          password: mypassword
          database: mydb
        primary:
          metrics:
            enabled: true
            service:
              ports:
                - name: metrics
                  port: 9187
                  targetPort: metrics
            serviceMonitor:
              enabled: true
              namespace: monitoring
              interval: 30s
              additionalLabels:
                release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true