apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.4.9
      values: |
        auth:
          username: myuser
          password: mypassword
          database: mydb
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: monitoring
            interval: 30s
            additionalLabels:
              release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
