grafana:
  replicas: 2
  persistence:
    enabled: true
    size: 500Mi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    type: pvc

prometheus:
  prometheusSpec:
    replicas: 2
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 500Mi

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
